# 1. Importing necessary libraries

In [1]:
import pandas as pd# fro preparing dataframe
import numpy as np
import matplotlib.pyplot as plt # for visualizing clusters
from matplotlib import style
style.use("ggplot") # choosing the style for visualising clusters
from scipy.cluster.hierarchy import linkage,dendrogram #descriptive analytic 
from sklearn.cluster import KMeans #Descriptive analytic algorithm
from sklearn import preprocessing # for preparing data
from sklearn.preprocessing import Normalizer # For Normalizing data
from numpy import set_printoptions # for limiting number decimals
from sklearn.decomposition import PCA # for reducing attributes
from sklearn.model_selection import train_test_split
import seaborn as sns; sns.set()

# 2. Extracting data

In [2]:
path='C:/Users/User/Desktop/Data/datafinale.csv'
attributes=['Molecular_Weight','Gravity','Aromaticity','Instability','Isoelectic_Point','Compartment']
data=pd.read_csv(path, names=attributes)
print(data)

      Molecular_Weight   Gravity  Aromaticity  Instability  Isoelectic_Point  \
0           93323.4594 -0.213571     0.075000    33.803119          5.995056   
1           27949.8955 -0.740000     0.077551    48.864980          4.799377   
2           17453.7134 -0.450327     0.098039    37.247124          6.489685   
3           35268.1468 -0.009366     0.063444    30.649245          8.177429   
4           25718.5138 -0.406912     0.142857    36.475576          8.082214   
5          120634.5465 -0.098273     0.088182    34.071391          6.960754   
6          250774.6466 -0.300983     0.082700    40.815919          5.869080   
7           36569.4096 -0.055917     0.082840    19.513609          7.596985   
8           25318.1366 -0.447727     0.081818    37.295909          8.694397   
9           48297.1855 -0.343678     0.071264    33.785310          8.733215   
10          42137.1258 -0.597855     0.107239    44.941019          6.640320   
11          58065.7220  0.008534     0.0

# 3. Understanding Data

In [3]:
print(data.describe())

       Molecular_Weight      Gravity  Aromaticity  Instability  \
count        1475.00000  1475.000000  1475.000000  1475.000000   
mean        58000.18511    -0.505198     0.074698    47.049551   
std         47394.06149     0.360483     0.027155    17.962127   
min          5966.91840    -2.657143     0.000000    -6.006803   
25%         29681.29515    -0.687294     0.057268    37.276526   
50%         46481.27160    -0.473278     0.073846    44.776744   
75%         71091.88025    -0.281112     0.090040    54.921842   
max        538812.43550     1.224138     0.227586   296.409091   

       Isoelectic_Point  
count       1475.000000  
mean           7.311856  
std            1.839831  
min            3.605530  
25%            5.760193  
50%            6.895813  
75%            8.871643  
max           13.366028  


# 4. Split Input and Output Features

In [4]:
TrainingSample,TestSample=train_test_split(data, test_size=0.3, random_state=2 ) #default is 25% starts at row number 2
print ("Training Set")
print(TrainingSample)
print("Testing Sample")
print(TestSample)

Training Set
      Molecular_Weight   Gravity  Aromaticity  Instability  Isoelectic_Point  \
1015        33329.2898 -0.259517     0.033233    45.541994          9.632019   
347         83465.6305 -0.313352     0.178977    42.173977          6.038513   
1324        58320.2209 -0.802857     0.051429    60.343619          8.489685   
682         46342.5275 -0.296905     0.095238    39.080500          8.287903   
945         17393.5577 -0.706918     0.056604    76.659182          9.715027   
658         29789.1132 -0.423792     0.078067    31.026022         10.234070   
1139        63028.6796 -0.844528     0.107547    57.322830          6.068542   
391         24144.7425 -0.292891     0.137441    38.633649          9.000549   
1268        37370.5698 -0.625698     0.050279    60.878799          7.252136   
116         20009.0449 -0.776879     0.098266    44.145087          5.162170   
104         44019.4249 -0.312437     0.086294    30.765736          8.567566   
1198        54192.9691 -0.1

# 5. Splitting Input and Output Variables

### Slice the input variables Data

In [5]:
Training_InputVariables=TrainingSample.values[:,0:5]

### Slice the Output Variable Data

In [6]:
Training_OutputVariable=TrainingSample.values[:,5]

In [7]:
print("Input Variables of Training Data")
print (Training_InputVariables)
print("Output Variables of Training Data")
print (Training_OutputVariable)

Input Variables of Training Data
[[33329.2898 -0.25951661600000003 0.033232628 45.54199396 9.632019043]
 [83465.6305 -0.313352273 0.17897727300000002 42.17397727 6.038513184]
 [58320.2209 -0.802857143 0.051428571 60.34361905 8.489685059]
 ...
 [20666.927 -0.445303867 0.154696133 30.20939227 6.888000487999999]
 [60234.0316 -0.184934087 0.103578154 49.5194162 9.045593262]
 [46867.013 -0.36116279100000004 0.065116279 61.61488372 7.635314941]]
Output Variables of Training Data
['Nucleus' 'Extracellular' 'Nucleus' ... 'Extracellular' 'Mitochondria'
 'Nucleus']


# 6. Splitting Test Input and Output Variables

### Slice the input variables Data

In [8]:
Test_InputVariables=TestSample.values[:,0:5]

### Slice the Output Variable Data

In [9]:
Test_OutputVariable=TestSample.values[:,5]

In [10]:
print("Input Variables of Test Data")
print (Test_InputVariables)
print("Output Variables of Test Data")
#print (Test_OutputVariable)

Input Variables of Test Data
[[50667.4842 -0.383482143 0.071428571 57.73102679 5.698669434]
 [55461.9333 -0.706626506 0.048192770999999995 72.29859438 6.154602051]
 [100591.0879 -0.75862069 0.052280310999999996 50.91370412 6.465759277]
 ...
 [59506.7141 -0.11050656699999999 0.075046904 35.15440901 8.506408691]
 [31361.8728 -0.46134751799999996 0.07092198599999999 48.69255319
  4.74017334]
 [81749.0863 -0.264754098 0.07377049200000001 53.49262295
  7.766906737999999]]
Output Variables of Test Data


# 6. Data Preprocessing

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

### Fit only to the training data

In [12]:
scaler.fit(Training_InputVariables)
Training_InputVariables= scaler.transform(Training_InputVariables)
Test_InputVariables= scaler.transform(Test_InputVariables)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


# 7. Fitting Decision Tree Classifier


In [13]:
# Loading Libraries
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier



### Build a tree model of three layers


In [14]:
tree_model= DecisionTreeClassifier (criterion="entropy", random_state=5, max_depth=3, min_samples_leaf=5, max_leaf_nodes=7)

# 8. Training The model

In [15]:
tree_model.fit(Training_InputVariables, Training_OutputVariable)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=7, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=5, splitter='best')

In [16]:
# Visualising of Decision Tree Model

# from sklearn.externals.six import StringIO
# from IPython.display import Image
# from sklearn.tree import export_graphviz
# import pydotplus
# data_feature_names=['Molecular_Weight','Gravity','Aromaticity','Instability','Isoelectic_Point']
# targetnames=['Cytosol','Extracellular','Mitochondria']

# dot_data=StringIO()
# export_graphviz(tree_model,feature_names=data_feature_names,out_file=dot_data, class_names=targetnames,filled=True, rounded=True, special_characters=True)
# graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
# print(Image(graph.create_png()))
# graph.write_pdf("Dtree.pdf")
# graph.write_png("Dtree.png")


In [17]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import tree
#from sklearn.datasets import load_wine
from IPython.display import SVG
from sklearn.tree import export_graphviz
#from graphviz import Source
import pydotplus
from IPython.display import display
# load dataset
#data = data

# feature matrix
#X = Training_InputVariables #data.data

# target vector
#y = Training_OutputVariable #data.target

# class labels
#attributes=['Molecular_Weight','Gravity','Aromaticity','Instability','Isoelectic_Point']
#labels = data.attributes

# print dataset description
#print(data.DESCR)
#estimator = DecisionTreeClassifier()
#estimator.fit(X, y)

#graph = Source(tree.export_graphviz(estimator, out_file=None
#   , attributes=labels, class_names=['0', '1', '2','3','4'] 
#   , filled = True))
# display(SVG(graph.pipe(format='svg')))

# 9. predict the first record

In [18]:
prediction1=tree_model.predict([[79443.7256,-0.594714286,0.058571429,41.76828571,4.912902832]])
print(prediction1)


['Nucleus']


# 10. Predict all the records of test data

In [19]:
Testdata_predictions=tree_model.predict(Test_InputVariables)
print(Testdata_predictions)

['Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Cytosol' 'Cytosol'
 'Mitochondria' 'Cytosol' 'Nucleus' 'Cytosol' 'Cytosol' 'Cytosol'
 'Nucleus' 'Nucleus' 'Mitochondria' 'Nucleus' 'Cytosol' 'Nucleus'
 'Cytosol' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Cytosol'
 'Mitochondria' 'Nucleus' 'Mitochondria' 'Nucleus' 'Cytosol' 'Cytosol'
 'Mitochondria' 'Nucleus' 'Cytosol' 'Cytosol' 'Mitochondria' 'Cytosol'
 'Nucleus' 'Cytosol' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus'
 'Cytosol' 'Nucleus' 'Mitochondria' 'Mitochondria' 'Cytosol' 'Nucleus'
 'Cytosol' 'Mitochondria' 'Nucleus' 'Nucleus' 'Nucleus' 'Cytosol'
 'Nucleus' 'Nucleus' 'Nucleus' 'Cytosol' 'Cytosol' 'Mitochondria'
 'Nucleus' 'Cytosol' 'Mitochondria' 'Cytosol' 'Nucleus' 'Mitochondria'
 'Nucleus' 'Nucleus' 'Cytosol' 'Nucleus' 'Cytosol' 'Nucleus' 'Cytosol'
 'Cytosol' 'Cytosol' 'Cytosol' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus'
 'Nucleus' 'Mitochondria' 'Nucleus' 'Cytosol' 'Nucleus' 'Cytosol'
 'Nucleus' 'Cytosol' 'Nucleus' 'Nucleus' 

# 12. Evaluating The Decision Tree Model

In [20]:
from sklearn.metrics import accuracy_score
Testdata_predictions=tree_model.predict(Test_InputVariables)
print("Accuracy is")
ModelAccuracy=accuracy_score(Testdata_predictions, Test_OutputVariable)*100
print(ModelAccuracy)


Accuracy is
59.14221218961625


# 13. Making the Confusion Matrix

In [21]:
from sklearn.metrics import classification_report,confusion_matrix
cm = confusion_matrix(Test_OutputVariable, Testdata_predictions)
cm


array([[ 59,   0,   6,  35],
       [ 21,   0,   6,  20],
       [ 19,   0,  27,  25],
       [ 30,   0,  19, 176]], dtype=int64)

# 14. Classification report to evaluate how well our model performed:

In [22]:
print(classification_report(Test_OutputVariable,Testdata_predictions))

               precision    recall  f1-score   support

      Cytosol       0.46      0.59      0.52       100
Extracellular       0.00      0.00      0.00        47
 Mitochondria       0.47      0.38      0.42        71
      Nucleus       0.69      0.78      0.73       225

    micro avg       0.59      0.59      0.59       443
    macro avg       0.40      0.44      0.42       443
 weighted avg       0.53      0.59      0.56       443



C:\Users\User\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# 15. Predict all the records of unknown data

### extracting unknown data

In [23]:
path='C:/Users/User/Desktop/Data/test_data_for_classification.csv'
attributes=['Molecular_Weight','Gravity','Aromaticity','Instability','Isoelectic_Point','Compartment']
unknowndata=pd.read_csv(path, names=attributes)
#print(unknowndata)

### Understanding unknown Data

In [24]:
print(unknowndata.describe())

       Molecular_Weight    Gravity  Aromaticity  Instability  Isoelectic_Point
count         20.000000  20.000000    20.000000    20.000000         20.000000
mean       41537.690505  -0.330752     0.078720    41.165265          7.779529
std        18373.515303   0.352151     0.023730    12.849688          1.896563
min        14352.000700  -1.101833     0.048649    23.574262          4.019226
25%        32644.786975  -0.631219     0.059577    31.610169          6.357452
50%        39574.256050  -0.185042     0.072829    38.692497          8.357605
75%        49286.619425  -0.095838     0.102079    49.454036          9.439514
max        85515.797200   0.251081     0.123894    72.129532         10.125305


### Splitting The Independent/Input Variables in Unknown Data Set

In [25]:
Unknown_InputVariables=unknowndata.values[:,0:5]
print(Unknown_InputVariables)

[[40263.0269 0.25108108100000004 0.048648649 60.33513514 5.877868652]
 [39617.6499 -0.102259887 0.10451977400000001 38.79129944
  5.084777831999999]
 [45866.9224 -0.112106538 0.075060533 35.49200969 5.832702637000001]
 [54961.4351 -1.101832994 0.059063135999999995 72.12953157 9.216491699]
 [14755.7075 -0.658208955 0.052238806 41.93955224 9.836486816]
 [34945.3058 -0.7802589 0.058252427 47.93398058 9.045471191]
 [51543.7667 -0.765470852 0.11659192800000001 30.09105381 9.405334473]
 [34516.1377 -0.683962264 0.059748428 57.70345912 9.849182128999999]
 [31408.4965 -0.622222222 0.107407407 31.58740741 6.441711426]
 [82535.3139 -0.215860215 0.060483870999999995 39.33239247 6.518981934]
 [39530.8622 -0.096952909 0.07479224400000001 31.61775623 6.425354004]
 [85515.7972 -0.46693333299999995 0.10666666699999999 41.17746667
  6.153747559]
 [40511.6111 -0.15422343300000002 0.065395095 31.92234332 9.004089355]
 [35031.2335 -0.092492492 0.05105105099999999 38.59369369 9.542053223]
 [53409.2222 -0.1

# 16. Predicting Unknown

In [26]:
Unknowndata_predictions=tree_model.predict(Unknown_InputVariables)
print(Unknowndata_predictions)

['Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus'
 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus'
 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus']
