# 1. Importing necessary libraries

In [47]:
import pandas as pd# fro preparing dataframe
import numpy as np
import matplotlib.pyplot as plt # for visualizing clusters
from matplotlib import style
style.use("ggplot") # choosing the style for visualising clusters
from scipy.cluster.hierarchy import linkage,dendrogram #descriptive analytic 
from sklearn.cluster import KMeans #Descriptive analytic algorithm
from sklearn import preprocessing # for preparing data
from sklearn.preprocessing import Normalizer # For Normalizing data
from numpy import set_printoptions # for limiting number decimals
from sklearn.decomposition import PCA # for reducing attributes
from sklearn.model_selection import train_test_split


# 2. Extracting data

In [48]:
path='C:/Users/User/Desktop/Data/datafinale.csv'
attributes=['Molecular_Weight','Gravity','Aromaticity','Instability','Isoelectic_Point','Compartment']
data=pd.read_csv(path, names=attributes)
print(data)

      Molecular_Weight   Gravity  Aromaticity  Instability  Isoelectic_Point  \
0           93323.4594 -0.213571     0.075000    33.803119          5.995056   
1           27949.8955 -0.740000     0.077551    48.864980          4.799377   
2           17453.7134 -0.450327     0.098039    37.247124          6.489685   
3           35268.1468 -0.009366     0.063444    30.649245          8.177429   
4           25718.5138 -0.406912     0.142857    36.475576          8.082214   
5          120634.5465 -0.098273     0.088182    34.071391          6.960754   
6          250774.6466 -0.300983     0.082700    40.815919          5.869080   
7           36569.4096 -0.055917     0.082840    19.513609          7.596985   
8           25318.1366 -0.447727     0.081818    37.295909          8.694397   
9           48297.1855 -0.343678     0.071264    33.785310          8.733215   
10          42137.1258 -0.597855     0.107239    44.941019          6.640320   
11          58065.7220  0.008534     0.0

# 3. Understanding Data

In [49]:

print(data.describe())

       Molecular_Weight      Gravity  Aromaticity  Instability  \
count        1475.00000  1475.000000  1475.000000  1475.000000   
mean        58000.18511    -0.505198     0.074698    47.049551   
std         47394.06149     0.360483     0.027155    17.962127   
min          5966.91840    -2.657143     0.000000    -6.006803   
25%         29681.29515    -0.687294     0.057268    37.276526   
50%         46481.27160    -0.473278     0.073846    44.776744   
75%         71091.88025    -0.281112     0.090040    54.921842   
max        538812.43550     1.224138     0.227586   296.409091   

       Isoelectic_Point  
count       1475.000000  
mean           7.311856  
std            1.839831  
min            3.605530  
25%            5.760193  
50%            6.895813  
75%            8.871643  
max           13.366028  


# 4. Split Training and Test Data Set

In [50]:
TrainingSample,TestSample=train_test_split(data, test_size=0.2, random_state=2 ) #default is 25% starts at row number 2
print ("Training Set")
print(TrainingSample)
print("Testing Sample")
print(TestSample)

Training Set
      Molecular_Weight   Gravity  Aromaticity  Instability  Isoelectic_Point  \
1416        19487.2768 -0.858192     0.039548    64.193785          5.152649   
1427        18451.9891 -0.512651     0.066265    60.777108          9.658264   
402         25703.5918  0.243083     0.075099    43.735573          9.020203   
285         51609.9517 -0.494503     0.059197    52.722833          6.712830   
194         85004.5028 -0.431629     0.091521    31.863257          7.241882   
1468        24425.1972 -0.667111     0.022222    51.563556          7.973328   
932         77735.7900 -0.778717     0.061224    59.129883          6.657166   
886         31409.5489 -0.842561     0.100346    66.415260          8.493835   
1329        74747.1439 -0.351510     0.133545    39.051685          8.501038   
498         42116.7654  0.018898     0.049869    58.322310          5.269836   
1121        44914.4626 -0.345093     0.049065    68.789252          6.418396   
732         35596.0269  0.1

# 5. Splitting Input and Output Variables

Slice the input and Output Training variables Data

In [51]:


Training_InputVariables=TrainingSample.values[:,0:5]

# Slice the Output Variable Data
Training_OutputVariable=TrainingSample.values[:,5]
print("Input Variables of Training Data")
#print (Training_InputVariables)
print("Output Variables of Training Data")
#print (Training_OutputVariable)

Input Variables of Training Data
Output Variables of Training Data


## Splitting Input and Output Test Variables


In [52]:
# Slice the input variables Data
Test_InputVariables=TestSample.values[:,0:5]

# Slice the Output Variable Data
Test_OutputVariable=TestSample.values[:,5]
print("Input Variables of Test Data")
#print (Test_InputVariables)
print("Output Variables of Test Data")
#print (Test_OutputVariable)

Input Variables of Test Data
Output Variables of Test Data


# 6. Data Preprocessing


The neural network in Python may have difficulty converging before the maximum number of iterations allowed if the data is not normalized.
Multi-layer Perceptron is sensitive to feature scaling so it is highly recommended to scale your data. 
Note that you must apply the same scaling to the test set for meaningful results. 
There are a lot of different methods for normalization of data, we will use the built-in StandardScaler for standardization.

In [53]:
from sklearn.preprocessing import StandardScaler

In [54]:
scaler = StandardScaler()

In [55]:
# Fit only to the training data
scaler.fit(Training_InputVariables)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [56]:
# Now apply the transformations to the data:
Training_InputVariables= scaler.transform(Training_InputVariables)
Test_InputVariables= scaler.transform(Test_InputVariables)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


# 7. Importing and Training Models
 
We will import our estimator (the Multi-Layer Perceptron Classifier model) from the neural_network library of SciKit-Learn!

In [57]:
from sklearn.neural_network import MLPClassifier

Next we create an instance of the model, 
we define the hidden_layer_sizes. 
For this parameter you pass in a tuple consisting of the number of neurons you want at each layer,
where the nth entry in the tuple represents the number of neurons in the nth layer of the MLP model. 
There are many ways to choose these numbers, 
We choose 3 layers with the same number of neurons as there are features in our data set along with 500 max iterations.

In [58]:

mlp = MLPClassifier(hidden_layer_sizes=(5,5,5),max_iter=500)

In [59]:
# Now that the model has been made we can fit the training data to our model, 
# remember that this data has already been processed and scaled:

mlp.fit(Training_InputVariables,Training_OutputVariable)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 5, 5), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

# 8. Predictions and Evaluation

In [60]:
# Now that we have a model we use it to get predictions! 
# We can do this simply with the predict() method off of our fitted model:

predictions = mlp.predict(Test_InputVariables)
print(predictions)

['Nucleus' 'Nucleus' 'Nucleus' 'Cytosol' 'Cytosol' 'Cytosol' 'Nucleus'
 'Extracellular' 'Nucleus' 'Cytosol' 'Cytosol' 'Cytosol' 'Mitochondria'
 'Nucleus' 'Nucleus' 'Nucleus' 'Extracellular' 'Cytosol' 'Nucleus'
 'Nucleus' 'Mitochondria' 'Nucleus' 'Nucleus' 'Nucleus' 'Cytosol'
 'Mitochondria' 'Nucleus' 'Cytosol' 'Nucleus' 'Cytosol' 'Cytosol'
 'Nucleus' 'Nucleus' 'Nucleus' 'Cytosol' 'Cytosol' 'Extracellular'
 'Nucleus' 'Cytosol' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus'
 'Cytosol' 'Nucleus' 'Nucleus' 'Mitochondria' 'Cytosol' 'Nucleus'
 'Cytosol' 'Mitochondria' 'Cytosol' 'Nucleus' 'Nucleus' 'Extracellular'
 'Cytosol' 'Nucleus' 'Nucleus' 'Cytosol' 'Nucleus' 'Mitochondria'
 'Nucleus' 'Cytosol' 'Mitochondria' 'Cytosol' 'Nucleus' 'Cytosol'
 'Nucleus' 'Nucleus' 'Cytosol' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus'
 'Cytosol' 'Cytosol' 'Cytosol' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus'
 'Nucleus' 'Mitochondria' 'Nucleus' 'Nucleus' 'Mitochondria' 'Cytosol'
 'Nucleus' 'Nucleus' 'Nucleus' 'Nucle

In [61]:
# Evaluating The Multi-Layer Perceptron Model
from sklearn.metrics import accuracy_score
Testdata_predictions=mlp.predict(Test_InputVariables)
print("Accuracy is")
ModelAccuracy=accuracy_score(Testdata_predictions, Test_OutputVariable)*100
print(ModelAccuracy)

Accuracy is
65.76271186440678


In [62]:
# Now we can use SciKit-Learn’s built in metrics such as a classification report and confusion matrix to evaluate how well our model performed:
from sklearn.metrics import classification_report,confusion_matrix

In [63]:
print(confusion_matrix(Test_OutputVariable,predictions))

[[ 36   3   3  21]
 [ 19   2   3   8]
 [ 11   1  21  12]
 [ 14   1   5 135]]


In [64]:
print(classification_report(Test_OutputVariable,predictions))

               precision    recall  f1-score   support

      Cytosol       0.45      0.57      0.50        63
Extracellular       0.29      0.06      0.10        32
 Mitochondria       0.66      0.47      0.55        45
      Nucleus       0.77      0.87      0.82       155

    micro avg       0.66      0.66      0.66       295
    macro avg       0.54      0.49      0.49       295
 weighted avg       0.63      0.66      0.63       295



In [65]:
# 12. Predict all the records of Unknown data
# extracting Unknown data
path='C:/Users/User/Desktop/Data/test_data_for_classification.csv'
attributes=['Molecular_Weight','Gravity','Aromaticity','Instability','Isoelectic_Point','Compartment']
unknowndata=pd.read_csv(path, names=attributes)
#print(unknowndata)

In [66]:
# 13. Understanding unknown Data
print(unknowndata.describe())

       Molecular_Weight    Gravity  Aromaticity  Instability  Isoelectic_Point
count         20.000000  20.000000    20.000000    20.000000         20.000000
mean       41537.690505  -0.330752     0.078720    41.165265          7.779529
std        18373.515303   0.352151     0.023730    12.849688          1.896563
min        14352.000700  -1.101833     0.048649    23.574262          4.019226
25%        32644.786975  -0.631219     0.059577    31.610169          6.357452
50%        39574.256050  -0.185042     0.072829    38.692497          8.357605
75%        49286.619425  -0.095838     0.102079    49.454036          9.439514
max        85515.797200   0.251081     0.123894    72.129532         10.125305


In [67]:
# Splitting Input/X Unknown Data
# Slice the input variables Data
X_Unknown=unknowndata.values[:,0:5]

In [68]:
# Fit only to the Unknown data
scaler.fit(X_Unknown)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [69]:
# Now apply the transformations to the Unknown data:
X_Unknown= scaler.transform(X_Unknown)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [70]:
predictions = mlp.predict(X_Unknown)
print(predictions)

['Nucleus' 'Cytosol' 'Cytosol' 'Nucleus' 'Nucleus' 'Nucleus' 'Nucleus'
 'Nucleus' 'Cytosol' 'Cytosol' 'Cytosol' 'Nucleus' 'Mitochondria'
 'Nucleus' 'Mitochondria' 'Nucleus' 'Cytosol' 'Cytosol' 'Extracellular'
 'Cytosol']
